name: dispatch
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  simple_animations: ^5.2.0
  page_transition: ^2.2.1
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1 #
  get: ^4.7.2
  connectivity_plus: ^6.1.4 #internet connection
  gif: ^2.3.0
  flutter_svg: ^2.2.0
#  carousel_slider: ^5.1.1
  camera: ^0.10.6 # don't update
  permission_handler: ^12.0.1
  google_mlkit_face_detection: ^0.12.0 # don't update
  facelivenessdetection: ^1.1.15
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2 # don't update
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  google_mlkit_text_recognition: ^0.14.0 # don't update
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  intl: ^0.20.2
  read_pdf_text: ^0.3.1
  device_info_plus: ^11.5.0
  kyc_workflow:
    path: libraries/kyc_workflow

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/jpg/
    - assets/animations/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins-regular.ttf
        - asset: assets/fonts/poppins-bold.ttf
        - asset: assets/fonts/poppins-light.ttf
        - asset: assets/fonts/poppins-semibold.ttf
#flavors:
#  dev:
#    name: "Development"
#    package: "com.dispatchsolutions.live_dev"
#    appname: "Dispatch Dev"
#    description: "Development build of the app"
#  prod:
#    name: "Production"
#    package: "com.dispatchsolutions.live"
#    appname: "Dispatch"
#    description: "Production build of the app"
